version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev
    platform: linux/amd64
volumes:
  node_modules:

