version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bash run.sh
    platform: linux/amd64
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tonstatus
      - MONGO_INITDB_ROOT_PASSWORD=tonstatus
volumes:
  node_modules:

